# Introduction {#Intro}

## Introduction

Nuclear cross-sections are fundamental material properties describing the interactions of radiation with matter. Accurate characterisations of cross-sections are essential for computer simulations of radiation effects, which are used extensively in applications such as medical technology, energy and defence. Detailed energy-dependent cross-section spectra are commonly generated using a synthesis of computer simulation and experimental observations, in a process known as evaluation. Part of this process consist of deciding at what values of the simulator input parameters to run it at. This aspect of evaluation is the focus of this work.

In this dissertation Bayesian history matching [@jeremy_histmatch; @bower2010galaxy] was examined as a tool for nuclear data evaluation. This involves identifying values of input parameters for computer simulators which give non-implausible outputs given relevant observations and all sources of uncertainty, such as the imprecision of the experimental measurement process, or the inability of the simulator to exactly reproduce the physical process it is intended to model. To do the analysis it is required that the simulator output is examined for many different values of the input parameters. It is often not feasible to run the simulator enough times to do this, even for simulators with moderate run-times. Consequently a statistical emulator must be used to model the relationship between the simulator's input parameters and its outputs. This introduces another source of uncertainty, which is fully characterised using the emulator. 

This work was carried out in compliance with the research ethics approval process of Sheffield University as described in Appendix \@ref(ethics-approval). 


## Aim of the dissertation {#Background:aim}

The aim of the dissertation was to investigate history matching as a tool for nuclear data evaluation. The particular case study used was of neutrons incident upon an Iron-56 isotope with energies between 5 and 10 MeV.  Bayesian history matching  was used to iteratively discount regions in the input space and subsequently build improved emulators for the relationship between the simulator and its input parameters in input regions of interest.


## Structure of the dissertation

The structure of the rest of the dissertation is as follows. In Chapter \@ref(Background) some background on nuclear data is presented, with discussion on the availability of relevant experimental data and nuclear reaction software. History matching is described in Chapter \@ref(History-Matching) and a notation is developed. In Chapter \@ref(GPR) an important component of history matching, Gaussian process regression, is described, and the relative merits of different software implementations are discussed. In Chapter \@ref(results) the first wave of history matching analysis is described in some detail, followed by a summary of the analysis in subsequent waves. Finally in Chapter \@ref(Discussion) the results are summarised, with discussion on the limitations of the analysis and potential for further work.

